# Generated by Django 6.0.5 on 2026-06-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hair',
            name='aftercare',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hair',
            name='details_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hair',
            name='included',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hair',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nail',
            name='aftercare',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nail',
            name='details_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='nail',
            name='included',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nail',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
