# Generated by Django 6.0.5 on 2026-06-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hair_aftercare_hair_details_title_hair_included_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cosmetic', 'Cosmetic'), ('hair', 'Hair'), ('nails', 'Nails')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/')),
                ('details_title', models.CharField(blank=True, default='', max_length=120)),
                ('included', models.TextField(blank=True, default='')),
                ('aftercare', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Hair',
        ),
        migrations.DeleteModel(
            name='Nail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
